In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])  # Simple 1D array
print(arr)


[1 2 3 4 5]


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])  #Simple 2D array
print(matrix)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr[0])  # Prints the first element, which is 1

1


In [5]:
print(matrix[0, 1])  # Accesses the element at row 0, column 1, which is 2


2


In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr_plus_10 = arr + 10  # Add 10 to each element of the array
print(arr_plus_10)
#This is called vectorisation.

[11 12 13 14 15]


In [7]:
arr2 = np.array([5, 4, 3, 2, 1])
result = arr + arr2  # Adding corresponding elements from both arrays
print(result)

[6 6 6 6 6]


In [8]:
print(np.mean(arr))  # Get the mean (average) of the array
print(np.sum(arr))   # Get the sum of the array
print(np.max(arr))   # Find the maximum value in the array


3.0
15
5


In [9]:
arr_reshaped = arr.reshape(1, 5)  # Reshape to 1 row and 5 columns
print(arr_reshaped)

[[1 2 3 4 5]]


In [10]:
arr = np.array([1, 2, 3, 4])
arr = arr + 5  # Adds 5 to each element in the array
print(arr)


[6 7 8 9]


In [11]:
zeros_array = np.zeros((3, 3))  # 3x3 array of zeros
print(zeros_array)

ones_array = np.ones((2, 4))  # 2x4 array of ones
print(ones_array)

range_array = np.arange(0, 10, 2)  # Array from 0 to 10 with step of 2
print(range_array)

random_array = np.random.rand(3, 2)  # 3x2 array of random numbers between 0 and 1
print(random_array)
#np.zeros(): Create an array filled with zeros.
#np.ones(): Create an array filled with ones.
#np.arange(): Create an array with a range of values.
#np.random.rand(): Generate random numbers.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[[0.13715118 0.15194941]
 [0.92182005 0.38241565]
 [0.86707069 0.98576186]]
